### ISSUE TITLE
FOV

### ISSUE THREAD

**Issue by RealDJDM** [IceHacks/KrunkerCheatInjector#12]
Make like a FOV so that i dont go snapping all the time

**Comment by zbot473** [comment]
I think you mean a camera that isn't affected by aimbot

**Comment by RealDJDM** [comment]
Like where u can limit to where you shoot using a circle. Look at link

https://www.google.com/url?sa=i&source=images&cd=&ved=2ahUKEwiGn6f-i5zlAhURHzQIHUEFBW8QjRx6BAgBEAQ&url=https%3A%2F%2Fwww.unknowncheats.me%2Fforum%2F1629860-post5.html&psig=AOvVaw3Sxw7MniYbCLQHlGkvBgTK&ust=1571154292826739

**Comment by zbot473** [comment]
I see wym. First we should perfect aimbot though, its still pretty glitchy.
