### ISSUE TITLE
fatal error, it crashes when you look at enemy

### ISSUE THREAD

**Issue by XD493** [IceHacks/KrunkerCheatInjector#13]
freezin, when you looking at enemy`s

**Comment by XD493** [comment]
reproduction - get into the game and look into enemy to make aimbot work

**Comment by XD493** [comment]
btw icehacks give access to channels - this guy who u like#1208

**Comment by zbot473** [comment]
What does the console look like?

**Comment by zbot473** [comment]
Try the latest version

**Comment by IceHacks** [comment]
We are fixing
