### ISSUE TITLE
Please Add This

### ISSUE THREAD

**Issue by gavin9235** [IceHacks/KrunkerCheatInjector#14]
Can you add a setting where the aimbot doesn't aim for the head and it doesn't automatically shoot
 and even maybe the aimbot works when you aim through your sights

**Comment by XD493** [comment]
>using icehacks krunker cheat in 2k19
XDD

**Comment by gavin9235** [comment]
what the hell do you mean ofcourse im using krunker dumbass

**Comment by humphreygaming** [comment]
Already requested but apparently not happening soon
