### ISSUE TITLE
Aimbot and autoswitch

### ISSUE THREAD

**Issue by mo-rp** [IceHacks/KrunkerCheatInjector#2]
Aimbot is great since it works with automatic weapons too, but it aims a little above the head, so i constantly have to move my mouse down to hit shots.
autoswitch breaks if primary and secondary have to reload at the same time

**Comment by XD493** [comment]
^^^

**Comment by zbot473** [comment]
I could add a tuning value that moves the aim around. Also wdym by break?

**Comment by mo-rp** [comment]
> I could add a tuning value that moves the aim around. Also wdym by break?

it keeps switching between primary and secondary since they both need reloading

**Comment by mo-rp** [comment]
> I could add a tuning value that moves the aim around. Also wdym by break?

also, the aim bug only seems to happen in long range, as if theres some sort of bullet drop, like snipers in fortnite

**Comment by zbot473** [comment]
Reload doesn't matter anymore LMAO

**Comment by mo-rp** [comment]
wdym?

**Comment by mo-rp** [comment]
oh inf ammo woah

**Comment by mo-rp** [comment]
> Reload doesn't matter anymore LMAO

the inf ammo is only client sided so is annoying as you cant reload the legit bullets and stick with the actual remaining bullets
