### ISSUE TITLE
Latest version is detected

### ISSUE THREAD

**Issue by Anonamort** [IceHacks/KrunkerCheatInjector#21]
**Describe the bug**
Upon opening game you get the error asking if you have correct Chrome/FF version installed.

**Expected behavior**
Game to load.

**Screenshots**
N/A

**Version**
Latest

**Comment by griff2781** [comment]
Yes detected

**Comment by zbot473** [comment]
ok I will investigate

**Comment by griff2781** [comment]
Lol that was pretty fast for the krunker servers

**Comment by IceHacks** [comment]
Fixed
