### ISSUE TITLE
IceHacks Detected on Krunker

### ISSUE THREAD

**Issue by griff2781** [IceHacks/KrunkerCheatInjector#22]
**Describe the bug**
When loading game it says Failed To Load Game and make sure you are using the latest version of chrome or firefox.
**Expected behavior**
The Hack should be working perfectly and loading to the game 
**Screenshots**
![Screen Shot 2019-10-30 at 7 23 41 AM](https://user-images.githubusercontent.com/57005577/67854226-53641200-fae6-11e9-9f54-52659818101e.png)
**Version**
0.1.0

**Comment by PvrtyMnstr** [comment]
Krunker updated, hence the bug
