### ISSUE TITLE
Antivirus picks up a Trojan in the file. 

### ISSUE THREAD

**Issue by SwitchMe33** [IceHacks/KrunkerCheatInjector#24]
Trojan Virus In The File. 

![9f65b8ccf28cc49acbc20be52f3c6f73](https://user-images.githubusercontent.com/54261975/68063922-1e70de80-fce3-11e9-8483-bae321fc9c49.png)

**Version**
(ex: 1.1.0)

**Comment by IceHacks** [comment]
https://www.virustotal.com/gui/file/e247d9a71577f5520f69ca8ebed23f86eba66722b1d63540dac12742dc6b78d6/detection

Windows antivirus isn't the best. Use a better service.

This is what we call a false positive.

@SwitchMe33
