### ISSUE TITLE
New Version of Krunker, Hack doesn't work.

### ISSUE THREAD

**Issue by PvrtyMnstr** [IceHacks/KrunkerCheatInjector#25]
![image](https://user-images.githubusercontent.com/57184767/68130460-023a9080-fee1-11e9-9422-2959f3166c3c.png)

**Comment by humphreygaming** [comment]
Noted, will do as soon as ice is online

**Comment by griff2781** [comment]
Any update?

**Comment by ThePower1123** [comment]
Yep it dosent work sometimes the hack just bugs the game and i cant damage people anymore just dealing 1-5 dmg

**Comment by IceHacks** [comment]
I'll check it out. School.
