### ISSUE TITLE
ACCOUNT MARKED HACKER 

### ISSUE THREAD

**Issue by OXanaXO** [IceHacks/KrunkerCheatInjector#26]
You Kruker cheat is detected and account is marked HACKER.

**Comment by IceHacks** [comment]
That's your fault.

**Comment by IceHacks** [comment]
https://github.com/IceHacks/KrunkerCheatInjector/blob/master/TERMS.md 
Also, I don't agree with using cheats on an account.

**Comment by OXanaXO** [comment]
No not my fault,
I have created one new account to test
and you hack are revelated and not working good
even in guest accounts the damages are low

I was just trying to help, but if this is the answer, I won't do it anymore

**Comment by IceHacks** [comment]
Yes your fault
