### ISSUE TITLE
less damage

### ISSUE THREAD

**Issue by eimonpakzad** [IceHacks/KrunkerCheatInjector#27]
it does not make lot of damage
make it head shot

**Comment by PvrtyMnstr** [comment]
Same, it fucked up my acc :(

**Comment by IceHacks** [comment]
any proof?

**Comment by PvrtyMnstr** [comment]
10 Headshot revolver?, it also happens with any other gun(Sniper is 15 or less)
![image](https://user-images.githubusercontent.com/57184767/68168574-d514cf00-ff2e-11e9-913b-252722f74d1b.png)
