### ISSUE TITLE
Damage bug, revolver or other weapons is 5 or less damage(Sniper 15 or less)

### ISSUE THREAD

**Issue by PvrtyMnstr** [IceHacks/KrunkerCheatInjector#28]
![image](https://user-images.githubusercontent.com/57184767/68168706-4a809f80-ff2f-11e9-9f7f-e0807729a62a.png)

**Comment by IceHacks** [comment]
I'll look at it.

**Comment by IceHacks** [comment]
Fixed. Will release in a few minutes. @PvrtyMnstr
