### ISSUE TITLE
it did not change 

### ISSUE THREAD

**Issue by eimonpakzad** [IceHacks/KrunkerCheatInjector#30]
it did not change

**Comment by IceHacks** [comment]
I can confirm it did. I just played a round with the AK47 and won.

**Comment by eimonpakzad** [comment]
what gun is that in game

**Comment by IceHacks** [comment]
triggerman

**Comment by eimonpakzad** [comment]
you are lying i am dying what is your discord

**Comment by eimonpakzad** [comment]
aim at head

**Comment by eimonpakzad** [comment]
it does 7 damage

**Comment by IceHacks** [comment]
@eimonpakzad No. I just tried it again to make sure it wasn't patched. 37 damage.

**Comment by IceHacks** [comment]
It could be you need to clear your cache https://github.com/IceHacks/KrunkerCheatInjector/tree/v0.1.4

If you are using an account flagged as hacker log out.

**Comment by eimonpakzad** [comment]
you are right than you
