### ISSUE TITLE
Freezing ingame

### ISSUE THREAD

**Issue by windecks** [IceHacks/KrunkerCheatInjector#31]
When first going on the website, there is a connection error, with the game being full. This is an easy fix, I just reload the page or click on the "here" hyperlink. Everything works fine until you "click to join the game", and at that point most of the game freezes. The timer and kill-feed still work, however; it's just that I can't move around and I'm stuck at one spot on the map.

Sorry, no screenshots

I believe the version is the latest release?

**Comment by eimonpakzad** [comment]
![Screenshot 2019-11-06 at 9 59 19 AM](https://user-images.githubusercontent.com/35317687/68309342-4615cd00-007c-11ea-978f-91d6900a33fe.png)

**Comment by eimonpakzad** [comment]
can't move

**Comment by humphreygaming** [comment]
haven't seen before, will investigate

**Comment by ThePower1123** [comment]
Same here http://prntscr.com/ptb9ug

**Comment by PvrtyMnstr** [comment]
Same Prblm here

**Comment by IceHacks** [comment]
I'll check it out when I have the time.

**Comment by IceHacks** [comment]
Ok. found the issue. I will fix when I have the time today.

**Comment by eimonpakzad** [comment]
when

**Comment by IceHacks** [comment]
Whenever there is time.

**Comment by eimonpakzad** [comment]
like when

**Comment by eimonpakzad** [comment]
ok

**Comment by IceHacks** [comment]
https://github.com/IceHacks/KrunkerCheatInjector/releases/tag/v0.1.5

**Comment by eimonpakzad** [comment]
thank
