### ISSUE TITLE
Put feature requests here

### ISSUE THREAD

**Issue by IceHacks** [IceHacks/KrunkerCheatInjector#33]
I need to get my priorities straight. Please don't post things that cannot be done through an extension (infinite ammo, health cheat, invisibility, etc...)

icehacks.official@gmail.com
[+1 (413) 337-7759‬](tel://+1-413-337-7759‬)

**Comment by Juicysnail** [comment]
Is it possible for an artificial 360/720 spin? Not sure if extra points are still in the game. Also a hotkey to toggle on/off hacks would be nice. Sometimes when trying to move snapping on to others is disorienting, so that would fix it.

**Comment by IceHacks** [comment]
@Juicysnail definitely possible I believe from what I know about silent aiming.

**Comment by dsbingbong** [comment]
like what juicysnail said, could there be either a toggle hacks button or some sort of aim on shoot?

**Comment by IceHacks** [comment]
I didn't see that in his post. @Juicysnail Binds are coming soon (https://github.com/IceHacks/KrunkerCheatInjector#coming-soon). @dsbingbong I will see that a menu option for that get's added next update.

**Comment by eimonpakzad** [comment]
Maybe wallhack shot in the wall kill someone

**Comment by UglyzHacks** [comment]
@IceHacks Can you make a triggerbot please? If you lay your crosshair on somebody, it auto shoots. And can you make an esp toggle to turn it off/on? Also can you make the aimbot more smoother instead of it moving like jaggity? By jaggity i mean like its moving like 5 pixels everytime it aims at people. I also have a question, what is auto sights? Thank you for your time.

**Comment by IceHacks** [comment]
@UglyzHacks It has that feature already. Auto sights automatically hit the right mouse button to aim down sights.

**Comment by UglyzHacks** [comment]
@IceHacks i know it has that feature but it only works when the aimbot is on. can you add that when the aimbot is off please?

**Comment by hangtightkrunker** [comment]
**PANIC MODE** _or whatever you want to call it.._

Turns off all hacks when toggled, but when turned off, all hacks come back. Good when you want to record others blatantly cheating.

**Comment by hangtightkrunker** [comment]
**SILENTAIM**

Part of autoaim, aims to the closest player that is to your crosshair. Makes it not so blatant and head snappy.

**Comment by PvrtyMnstr** [comment]
Anti-Ban or something like that

**Comment by eimonpakzad** [comment]
KR HacK

**Comment by zbot473** [comment]
@PvrtyMnstr don't use an account lmao
@eimonpakzad impossible, that's server side
