### ISSUE TITLE
Freezing ingame has appeared again

### ISSUE THREAD

**Issue by windecks** [IceHacks/KrunkerCheatInjector#35]
Identical issue to the one brought up about 5(?) days ago. Freezing ingame, as if you can't move. Timer and kill-feed still work.

**Comment by eimonpakzad** [comment]
![Screenshot 2019-11-08 at 9 56 28 AM](https://user-images.githubusercontent.com/35317687/68485942-20203200-020e-11ea-8874-a54bcbbbf0d5.png)

**Comment by BLANKxSS** [comment]
me to

**Comment by PvrtyMnstr** [comment]
Krunker updated

**Comment by eimonpakzad** [comment]
when will it be fixed

**Comment by IceHacks** [comment]
Krunker updated and time zones: exist.
