### ISSUE TITLE
Game is not launching

### ISSUE THREAD

**Issue by DiamondsBattle** [IceHacks/KrunkerCheatInjector#36]
When I try to launch a game, I don't appear and the only thing on the screen is the background and the chat (and the kill log). I am actually in the game, because people can kill me. 😢 How can I fix this ?
I am on IceHacks 0.1.5 .

**Comment by dsbingbong** [comment]
this happened to me too

**Comment by IceHacks** [comment]
Please download the latest (v0.1.6) https://github.com/IceHacks/KrunkerCheatInjector/releases/latest
