### ISSUE TITLE
it is not working

### ISSUE THREAD

**Issue by eimonpakzad** [IceHacks/KrunkerCheatInjector#37]
![Screenshot 2019-11-14 at 8 08 25 PM](https://user-images.githubusercontent.com/35317687/68908948-c68e9a80-071a-11ea-85a8-6e0cbe2b4a03.png)

**Comment by IceHacks** [comment]
Ok, I'll check this out. I don't play krunker so thanks for letting me know.

**Comment by IceHacks** [comment]
Fixed, will update later :p
