### ISSUE TITLE
retarded aimbot 2 and broken switcher psychics

### ISSUE THREAD

**Issue by XD493** [IceHacks/KrunkerCheatInjector#4]
when you dont have ammo on 2 weapons it just switch along of this two and dont give a chance to reload
aimbot when you dont shot properly goes in retarded mode and spin around / try to shoot at zoom

**Comment by zbot473** [comment]
Reload doesnt matter anymore

**Comment by Lemons1337** [comment]
Reloading does matter #5

**Comment by IceHacks** [comment]
Please understand this is alpha. And our understanding of krunker is poor since we just started two days ago.

**Comment by XD493** [comment]
i know it, so i want to help you in this reporting a new bugs so you can fix it, we are gamers and we all have responsibility to help ourselfs
