### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by IronCS** [IceHacks/KrunkerCheatInjector#42]
1.9 was released, and now it doesnt load.

**Comment by IceHacks** [comment]
ok, I'll check it out later. I don't normally play krunker.

**Comment by ghost** [comment]
yeah it just stays on the loading page

**Comment by ghost** [comment]
lol i keep coming back every minute to check and hope its been fixed XD

**Comment by ghost** [comment]
> ok, I'll check it out later. I don't normally play krunker.

please check it out soon
:)

**Comment by IceHacks** [comment]
still haven't looked at it. No break for me.

**Comment by IceHacks** [comment]
Not as many people use this as my other cheats.

**Comment by ZaigoYT** [comment]
> Not as many people use this as my other cheats.

well people use it and youtubers make videos on your cheat

**Comment by IceHacks** [comment]
only @zbot473 is updating this rn
