### ISSUE TITLE
virus detected

### ISSUE THREAD

**Issue by SeekNDstroy565** [IceHacks/KrunkerCheatInjector#44]
My device has detected some kind of virus in this file. Whenever I download the file, a message saying it has virus in it pops up every single time. Is there any kind of virus in it or is it my computer's problem.🤨🤨🤨🤨

**Comment by zbot473** [comment]
What antivirus?

**Comment by IceHacks** [comment]
@zbot473 u r so tech support. It will do that on some services because of JS.
