### ISSUE TITLE
the hack does not work

### ISSUE THREAD

**Issue by SeekNDstroy565** [IceHacks/KrunkerCheatInjector#45]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Version**
(ex: 1.1.0)

**Comment by SeekNDstroy565** [comment]
the hack won't work on my computer. I mean the game is not even loading

**Comment by IceHacks** [comment]
it is known. read the readme and see that I am not working on this. I had it archived but zbot wanted to work on it.
