### ISSUE TITLE
Infinite Ammo is server sided

### ISSUE THREAD

**Issue by Lemons1337** [IceHacks/KrunkerCheatInjector#5]
You cannot have infinite ammo because everything is calculated on the server. It will appear as if you have infinite ammo but in reality it's just client sided meaning it won't affect game-play at all.

**Comment by anthony1895** [comment]
ok

**Comment by humphreygaming** [comment]
so what

**Comment by TheJustExper** [comment]
Have you figured out how to do the recoil adapter by bypassing the speed modulation module

**Comment by Lemons1337** [comment]
You'd need to demodulate the interpolated protocol buffer and reverse the polarity of the player velocity

**Comment by TheJustExper** [comment]
As long as you change your tickrate by using the polarity modifier which you would need to inject first then you can safely have unlimited ammo without the server re-modulating the ammo module  

TIS BASIK COMUN SENS

**Comment by zbot473** [comment]
@Lemons1337 bruh ur the only one smart enough lmao, kids on the internet won't know this

**Comment by zbot473** [comment]
A little bit of false advertisement = ez views

**Comment by Hoodgail** [comment]
@zbot473 I actually told @Lemons1337 about this 😆
