### ISSUE TITLE
slide bhop option

### ISSUE THREAD

**Issue by XD493** [IceHacks/KrunkerCheatInjector#7]
there are slide bhop, and its 420% faster

**Comment by IceHacks** [comment]
We are focusing on Aimbot right now I believe

**Comment by zbot473** [comment]
I tried

**Comment by mo-rp** [comment]
the slide bhop isnt good
it holds shift right as you press space and doesnt respond very well
make it so before you hit the ground, or maybe as you hit the ground, you press shift once and then jump again

**Comment by zbot473** [comment]
Not sure if there's a height attribute

**Comment by IceHacks** [comment]
Ye it is bad
