### ISSUE TITLE
quickscoper 

### ISSUE THREAD

**Issue by XD493** [IceHacks/KrunkerCheatInjector#8]
make aimbot quickscoping all time, no only when you shoot first time - it turns in zoom trying when you miss

**Comment by noodlychezzy** [comment]
Maybe add two options for aimbot,
one for auto weapons, like ar, smg, lmg, etc
one for non auto, eg sniper, revolver, rpg
we can toggle so we can use any weapon with no problem

**Comment by zbot473** [comment]
What would the difference be @noodlychezzy

**Comment by noodlychezzy** [comment]
on the auto weapon option, your scope will stay scoped in when an enemy is in target
on the non auto weapon option, you only quick scope at the player.

**Comment by qutm** [comment]
I think u should add no recoil then these hacks would be better then gaming chair

**Comment by zbot473** [comment]
@qutm 
Recoil is server side. Aimbot can account for it, but RN I want to focus on making aimbot good.
