### ISSUE TITLE
Are you trying to get the game patched?

### ISSUE THREAD

**Issue by skidlamer** [IceHacks/KrunkerCheatInjector#9]
What sort of an idiot comes along and exposes what we have been using for 3 updates due to stupid coding. **WHY ARE YOU WRITING THIS TO THE CONSOLE FFS**
exhibit a: 
**

> IT fixes it ASAP or IT gets the hose again!

**
https://i.imgur.com/bwQt4Nt.png

`
                'from': /https:\/\/shop\.spreadshirt\.com\/krunkerio/g,
                'to': 'https://www.youtube.com/channel/UCPxPCDp0sYnjZWEmfN9jHyQ'
            }, {
                'from': /\.\/img\/merch\.png/g,
                'to': _0x49d9('0x2')
            }, {
                'from': /merchImg"/g,
                'to': 'merchImg" style='
                border - radius: 200 px;
                ''
            }, {
                'from': /id="streamContainer"/g,
                'to': _0x49d9('0x3')
            }, {
                'from': /\.\/docs\/terms\.txt/g,
                'to': _0x49d9('0x4')
            }, {
                'from': /buttonP/g,
                'to': _0x49d9('0x5')
            }, {
                'from': /function o\(A,g\){return i\.decode\(c\(\)\.subarray\(A,A\+g\)\)/g,
                'to': '
                function o(A, g) {
                    var x = i.decode(c().subarray(A, A + g));
                    var p = [{
                            from: /tmpObj\['inView'\]/g,
                            to: "true"
                        },
                        {
                            from: /(\w+)\['exports'\]\['obj'\]=function\(((\w+[,]*){9})\){/g,
                            to: "$1['exports']['obj']=function($2){if (window.kjs) {window.kjs.scope=this};"
                        },
                        {
                            from: /{if\(this\['target'\]\){(.*?)}},/g,
                            to: "{if (!window.kjs) {location.reload()};window.kjs.input=this;if(this['target']){$1}},this.aim="
                        },
                        {
                            from: /this\['xDire'\]=\((.*?)\)\['round'\]\(0x3\)/g,
                            to: "this.xDire=(kjs.input.object.rotation.y % Math.PI2).round(3)"
                        },
                        {
                            from: /this\['yDire'\]=\((.*?)\)\['round'\]\(0x3\)/g,
                            to: "this.yDire=(kjs.input.pitchObject.rotation.x % Math.PI2).round(3)"
                        },
                        /*{
                        	from: /(\w+\['exports'\]\['camChase(Spd|Sen)\'])=.*?,/g,
                        	to: "$1 = 15000000,"
                        },*/
                        {
                            from: /(\w+\['exports'\]\['camChaseTrn\'])=.*?,/g,
                            to: "$1 = 0.03,"
                        },
                        {
                            from: /(\w+\['exports'\]\['camChaseDst\'])=.*?,/g,
                            to: "$1 = 0,"
                        },
                        {
                            from: /(this\['procInputs'\]=function\(\w+,\w+,\w+\)\{)/g,
                            to: "$1 kjs.start();"
                        },
                        {
                            from: /CLICK\\x20TO\\x20PLAY/g,
                            to: "CLICK TO USE ICEHACKS CHEAT"
                        }
                    ];
                    p.forEach((l) => {
                        if (x.match(l.from)) console.log(x.match(l.from));
                        x = x.replace(l.from, l.to)
                    });
                    return x;`

**Comment by XD493** [comment]
thats not place for you. chill, maybe some tea?

**Comment by zbot473** [comment]
Ok I removed it. I'm working on some features, so ill release later.

**Comment by billythejew456** [comment]
you should probably close the issue then

**Comment by IceHacks** [comment]
@skidlamer That was for testing, I was not here and @zbot473 didn't remove it before releasing. I doubt posting it on an open GitHub makes it any better tho. So you are both equally stupid rn.

**Comment by IceHacks** [comment]
Another thing, if you have your own cheats why use mine. Also:

"exhibit a:"
Your image has 23 views on Imgur and I'm sure this github issue has more
